openapi: 3.0.0
info:
  title: CEM scan API
  version: 1.0.0
  description: >-
    Trigger scan via public REST APIs.
  contact:
    name: CEM
servers:
  - url: https://api.cem.cyberark.cloud/api
    description: >-
      cem_base_url
  - url: https://{identity_tenant}.my.identity.qa
    description: >-
      identity_base_url
components:
  securitySchemes:
    bearerOAuth:
      type: http
      scheme: bearer
      description: ''
  responses:
    status:
      description: >-
        Scan's current status
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                enum: 
                  - NotRunning
                  - Running
                description: >-
                  Scan Status. Supported values: Not running, Running
    TriggerScanError:
      description: >-
        Trigger scan response
      content:
        application/json:
          schema:
            type: object
            properties:
              errorMessage:
                type: string
                description: >-
                  Holds trigger scan error message. Example: A scan failed to be triggered as another scan is already in progress.
paths:
  /scan:
    post:
      tags:
        - Operations
      summary: >-
        Trigger CEM scan on customer's tenant.
      security:
        - bearerOAuth: []
      responses:
        '200':
          description: A scan was  successfully triggered
        '500':
          description: Internal Server Error
      operationId: triggerScan
      description: "\t\nTrigger CEM scan on a customer's tenant"
  /scan/status:
    get:
      tags:
        - Operations
      summary: >-
        Returns the status of the scan. 
      security:
        - bearerOAuth: []
      responses:
        '200':
          $ref: '#/components/responses/status'
        '500':
          description: Internal Server Error
        '400':
          description: Bad request
      operationId: getStatus
      description: "\t\nReturns the status of the scan."  